def ok():
    print("      _")
    print("    _| |")
    print("  _| | |")
    print(" | | | |")
    print(" | | | | __")
    print(" | | | |/  \\")
    print(" |       /\ \\")
    print(" |      /  \/")
    print(" |      \  /\\")
    print(" |       \/ /")
    print("  \        /")
    print("   |     /")
    print("   |    |")
    print("")
